import { z } from 'zod'
import { labels, priorities, statuses } from './enums.js'

const autogenerated = { id: true, createdAt: true, updatedAt: true } as const

export const taskSchema = z.object({
  id: z.int().min(1),
  title: z.string(),
  label: z.enum(labels.map((_) => _.value)),
  status: z.enum(statuses.map((_) => _.value)),
  priority: z.enum(priorities.map((_) => _.value)),
  createdAt: z.date(),
  updatedAt: z.date(),
  assignee: z.string().optional(),
  description: z.string().optional(),
  dueDate: z.date().optional(),
})

export const mutatedTaskSchema = taskSchema.omit(autogenerated)

export type Task = z.infer<typeof taskSchema>
export type MutatedTask = z.infer<typeof mutatedTaskSchema>
